@startuml lol

Person <|-- Host
Person <|-- Player
Captain <|-- Player
Team "1" o-- "3..*" Player
Team "1" o-- "1" Captain
Club "1" o-- "1..*" Team 
Match "1" o-- "2" Team 
Division "1" *-- "1..*" Match  
Host ..> Division


class Person {
    Name
    SSN
    mobile_nr
}

class Player {
    address
    home_nr
    email
    team_id
}

class Host {

}

class Captain {
    post_results()
}

class Club {
    name
    address
    phone_nr
    teams_id[]
}

class Team {
    team_id
    name
    captain_id
    players_id[]
}

class Division {
    name
    team_id[]
    host_id
    start_date
    end_date
    type
    match[]
}

class Match {
    date
    division_id
    home_team
    home_team_players[]
    away_team
    away_team_players[]
    results
    add_results()
    change_results()
    postpone_match()
}

class TeamLL {
    get_team_txt( team_id )
    get_team( team_id )
}

class ClubLL {
    get_club_txt( club_id )
    get_club( club_id )
}

class DivisionLL{
    get_divisiom_txt( division_id )
    get_divisiom( division_id )
}

class MatchLL {
    get_match_txt( match_id )   
    get_match( match_id )   
}



@enduml