@startuml lol


Match "*"---"8" Player
Team "1" --- "3..*" Player
Club "1" --- "1..*" Team 
Match "*" --- "2" Team 
Division "1" -- "1..*" Match  
Club "1" ---"*" Player
Team "*"---"*" Division

class Player {
    id 
    club_id
    name 
    ssn
    mobile_nr
    home_nr
    address
    email
}
class Club {
    id
    teams_id[]
    name
    address
    phone_nr
}
class Team {
    id
    player_ids[]
    captain_id
    name
}
class Division {
    id
    team_ids[]
    match_ids[]
    name
    host_name
    phone_nr
    start_date
    end_date
    type
    rounds
}
class Match {
    id
    division_id
    home_team_id
    away_team_id
    date
    home_team_player_ids[]
    away_team_player_ids[]
    quality_points{}
    results[]
}

@enduml