@startuml lol


Team "1" o-- "3..*" Player
Club "1" *-- "1..*" Team 
Match "1" o-- "2" Team 
Division "1" *-- "1..*" Match  


class Player {
    name
    SSN
    mobile_nr
    address
    home_nr
    email
    team_id
    captain: bool
}
class Club {
    name
    address
    phone_nr
    teams_id[]
}
class Team {
    team_id
    name
    captain_id
    players_id[]
}
class Division {
    name
    team_id[]
    host_id
    start_date
    end_date
    type
    match[]
}
class Match {
    date
    division_id
    home_team
    home_team_players[]
    away_team
    away_team_players[]
    results
}

@enduml