@startuml lol


Team "1" o-- "3..*" Player
Club "1" *-- "1..*" Team 
Match "*" o-- "2" Team 
Division "1" *-- "1..*" Match  


class Player {
    id
    team_id
    name
    SSN
    mobile_nr
    home_nr
    address
    email
    captain: bool
}
class Club {
    id
    teams_id[]
    name
    address
    phone_nr
}
class Team {
    id
    player_ids[]
    captain_id
    name
}
class Division {
    id
    team_ids[]
    host_name
    phone_nr
    start_date
    end_date
    type
    rounds
}
class Match {
    id
    division_id
    type
    date
    home_team
    away_team
    home_team_players[]
    away_team_players[]
    results
    quality_points
}

@enduml