@startuml

class MainMenuUI  #B4a7e5 {
    LogicWrapper
    display_mainmenu()
    select_login()
}
class PostLoginMenuUI #B4a7e5 {
    LogicWrapper
    display_hostmenu()
    select()
}
class LeaderboardUI #B4a7e5 {
    LogicWrapper
    display()
    select()
    get_leaderboard()
}
class TeamsUI #B4a7e5{
    LogicWrapper
    display()
    select()
    edit_teams()
    create_team()
    get_team()
}
class UnplayedMatches #B4a7e5{
    LogicWrapper
    display()
    select()
    get_unplayed_matches()
}
class ResultsUI #B4a7e5{
    LogicWrapper
    display()
    select()
    get_results()
}
class DivisionTableUI #B4a7e5{
    LogicWrapper
    display()
    select()
    get_division_table()
}
class ClubsUI #B4a7e5{
    LogicWrapper
    display()
    select()
    create_new_club()
    edit_club()
    get_clubs()
}
class DivisionUI #B4a7e5{
    LogicWrapper
    display()
    select()
    create_division()
    add_team_to_division()
    edit_division()
    get_divison()
}
class MatchesUI #B4a7e5{
    LogicWrapper
    display()
    select()
    edit_match()
    add_match()
    view_scoreboard()
    get_matches()
}
class LoginMenuUI #B4a7e5{
    LogicWrapper
    display()
    select()
}

class PlayerUI #B4a7e5 {
    LogicWrapper
    display()
    select()
    remove_player()
    add_player()
    change_captain()
    get_players()
    get_player()
}

class ScoreboardUI #B4a7e5 {
    LogicWrapper
    display_scoreboard()
    add_scoreboard()
    edit_scoreboard()
    get_scoreboard()
}

class PersonLL #EB937F{
    Person
    PersonIO
    create_person()
    get_all_players()
    get_person( person_id )   
}

class MatchLL #EB937F{
    Match
    MatchIO
    create_match()
    get_all_matches()
    get_upcoming_matches()
    get_concluded_matches()
    change_date()
    set_results()
    change_results()
    get_match( match_id )   
}

class DivisionLL #EB937F {
    Division
    DivisionIO
    create_division()
    get_leaderboard()
    get_division( division_id )
}

class TeamLL #EB937F{
    Team
    TeamIO
    create_team()
    get_all_teams()
    get_team( team_id )
}

class ClubLL #EB937F {
    Club
    ClubIO
    create_club()
    get_club( club_id )
}

class LogicWrapper{
    TeamLL
    ClubLL
    DivisionLL
    MatchLL
    allexposedLLfunctions()
}



LogicWrapper -- TeamLL
LogicWrapper -- PersonLL
LogicWrapper -- ClubLL
LogicWrapper -- DivisionLL
LogicWrapper -- MatchLL

MainMenuUI  --  LogicWrapper
LeaderboardUI -- LogicWrapper
ScoreboardUI -- LogicWrapper
DivisionUI -- LogicWrapper
PostLoginMenuUI --  LogicWrapper
UnplayedMatches -- LogicWrapper
TeamsUI -- LogicWrapper
DivisionTableUI -- LogicWrapper
ClubsUI --  LogicWrapper
MatchesUI -- LogicWrapper
LoginMenuUI -- LogicWrapper
ResultsUI -- LogicWrapper
PlayerUI-- LogicWrapper



PersonLL -- StorageWrapper 
TeamLL -- StorageWrapper 
ClubLL -- StorageWrapper 
DivisionLL -- StorageWrapper 
MatchLL -- StorageWrapper 

/'
Storage layer
'/
class StorageWrapper{
    MatchIO
    PersonIO
    DivisionIO
    TeamIO
    PlayerIO
    allexposedIOfunctions()

}

class PersonIO #ADD1b2{
    persons_filename
    get_person_from_file()
    write_person_to_file()

}
class MatchIO #ADD1b2{
    match_filename
    get_match_from_file()
    write_match_to_file()

}
class DivisionIO #ADD1b2{
    get_division_from_file()
    write_division_person_to_file()
}
class TeamIO  #ADD1b2  {
    get_team_from_file()
    write_team_person_to_file()
}
class ClubIO  #ADD1b2 {
    get_club_from_file()
    write_club_person_to_file()

}

StorageWrapper -- MatchIO
StorageWrapper -- PersonIO
StorageWrapper -- DivisionIO
StorageWrapper -- TeamIO
StorageWrapper -- ClubIO

@enduml